import { Prisma } from "@prisma/client";
import type {
  Listing as ListingRow,
  Proposal as ProposalRow,
  SellerSettings as SellerSettingsRow,
} from "@prisma/client";
import { prisma } from "./prisma";

export type Platform = "ebay" | "depop" | "other";
export type ListingStatus = "draft" | "active" | "sold" | "stale" | "ended" | "scheduled";

/** One traffic reading, taken each time a live listing is synced from eBay. */
export interface TrafficPoint {
  views: number;
  watchers: number;
  at: string;
}

/**
 * Everything Depop-specific about a listing.
 *
 * Depop has no public listing API, so nothing here can be synced — every
 * field is either generated by us or typed in by the seller. Deliberately
 * NOT a second metrics store: views, likes, sold price and sold date all
 * live in `outcome` exactly as they do for eBay, so the playbook, diagnosis
 * and analytics read one shape and work for both platforms without knowing
 * which one a listing came from. (`outcome.watchers` holds Depop likes —
 * the same signal under a different name, surfaced with the right label.)
 */
/**
 * The Depop rewrite, shaped like Depop's compose form rather than eBay's.
 *
 * Declared here rather than inferred from the zod schema in lib/depop.ts so
 * that store.ts stays free of that import — the generator depends on the
 * store, not the other way round.
 */
export interface DepopDraft {
  description: string;
  hashtags: string[];
  brand: string;
  size: string;
  category: string;
  subcategory: string;
  condition: string;
  colour: string;
  source: string;
  age: string;
  price: number;
  priceNote: string;
  photoPlan: string[];
  vibe: string;
}

export interface DepopState {
  /** The Depop-optimized rewrite, shaped like Depop's compose form. */
  draft?: DepopDraft;
  generatedAt?: string;
  /** Set when the seller confirms they've actually posted it to Depop. */
  listedAt?: string;
  /**
   * Last time the seller refreshed the listing. Depop ranks on recency, so a
   * stale listing sinks in the feed and refreshing is the fix — but only the
   * seller can do it, and only they can tell us they did.
   */
  refreshedAt?: string;
  /** Link to the live listing, pasted by the seller. */
  url?: string;
}

export interface ListingOutcome {
  views: number;
  watchers: number;
  offers: number;
  soldPrice?: number;
  listedAt?: string;
  soldAt?: string;
  updatedAt: string;
  /**
   * Views/watchers over time rather than a single snapshot, so the proposal
   * engine can tell a listing that's dying in search from one that's simply
   * young, and a price that's close (watchers climbing, no sale) from one
   * that's wrong (views but no watchers at all).
   */
  trafficHistory?: TrafficPoint[];
}

/** What it cost to acquire and move an item — drives profit and margin. */
export interface CostBasis {
  /** What you paid for the item */
  purchasePrice?: number;
  /** Shipping you paid out (postage, packaging) */
  shippingCost?: number;
  /** Marketplace + payment fees */
  fees?: number;
  /** Where you sourced it, for spotting which sources pay off */
  source?: string;
  updatedAt: string;
}

export interface Comps {
  summary: string;
  priceLow?: number;
  priceHigh?: number;
  demandNotes: string;
  sources: string[];
  /** User-pasted comps when web research can't reach sold data */
  manualNotes?: string;
  at: string;
}

/** A single dimension of the listing quality breakdown. */
export interface ScoreDimension {
  dimension:
    | "title_keywords"
    | "item_specifics"
    | "price_vs_comps"
    | "description_trust"
    | "condition_clarity"
    | "photo_coverage"
    | "category_fit";
  score: number;
  detail: string;
}

export interface BrainScore {
  score: number;
  reason: string;
  /** Per-dimension breakdown; absent on old scores before this feature. */
  breakdown?: ScoreDimension[];
  at: string;
}

/** A structured item specific extracted from photos or seller input. */
export interface ItemSpecific {
  name: string;
  value: string;
  /** Where the fact came from: photo, tag, seller note, or AI inference. */
  source: "photo" | "tag" | "seller" | "inferred";
}

/** An eBay category aspect (required or recommended field). */
export interface EbayAspect {
  name: string;
  required: boolean;
  /** Example values eBay suggests for this aspect. */
  examples?: string[];
}

/** A record of an auto-relist cycle on eBay. */
export interface RelistRecord {
  oldItemId: string;
  newItemId: string;
  oldPrice: number;
  newPrice: number;
  at: string;
}

export interface Diagnosis {
  /** Why this listing isn't selling */
  text: string;
  rewrittenTitle: string;
  rewrittenDescription: string;
  suggestedPrice: number;
  at: string;
}

export interface Listing {
  id: string;
  platform: Platform;
  title: string;
  description: string;
  price: number;
  category: string;
  condition: string;
  tags: string[];
  /** What the photos show (or should show) */
  photosNote: string;
  status: ListingStatus;
  source: "imported" | "generated";
  outcome?: ListingOutcome;
  /** Depop draft + manual tracking state. See DepopState. */
  depop?: DepopState;
  cost?: CostBasis;
  comps?: Comps;
  brainScore?: BrainScore;
  diagnosis?: Diagnosis;
  /** "control" or the id of the active experiment this listing tests */
  experimentId?: string;
  /** Real eBay item ID (from the listing's URL) — lets us auto-sync outcome data */
  ebayItemId?: string;
  /** Stored photo ids (front, back, extras) served from /api/photos/[id] */
  photos?: string[];
  /**
   * Images hosted by eBay, for listings synced from the account rather than
   * created here. Kept separate from `photos`: those are ids we serve from
   * our own store, these are absolute URLs we do not own.
   */
  imageUrls?: string[];
  /** Set once we've published this listing to eBay from here */
  publishedAt?: string;
  /** SKU we generated when publishing via the eBay Inventory API */
  ebaySku?: string;
  /**
   * Inventory API offer id. Distinct from ebayItemId: the item id identifies
   * the public listing, the offer id is what the Inventory API acts on. Relist
   * withdraws by offer id, so without this we cannot end the old listing.
   */
  ebayOfferId?: string;
  /**
   * eBay's ListingType for a synced listing (FixedPriceItem, Chinese, ...).
   * Decides which Trading revise call is legal for it.
   */
  ebayListingType?: string;
  /** Structured item specifics (brand, size, color, etc.) for eBay aspects */
  itemSpecifics?: ItemSpecific[];
  /** Cached eBay category aspects — what fields eBay expects for this category */
  ebayAspects?: EbayAspect[];
  /** eBay category ID resolved during listing creation */
  ebayCategoryId?: string;
  /**
   * Weight and size of the item once packed for shipping. eBay refuses to
   * publish without a weight when the fulfillment policy prices postage by
   * calculated shipping, and the buyer is quoted from these numbers, so they
   * describe the packed parcel — mailer and padding included — not the bare
   * item. Dimensions are optional; weight is what eBay insists on.
   */
  packageWeightOz?: number;
  packageDimensionsIn?: { length: number; width: number; height: number };
  /** Real carrier + tracking once the sale has been shipped */
  shipping?: {
    carrier: string;
    trackingNumber: string;
    shippedAt: string;
    /** False when eBay wasn't updated (no linked item, or the call failed) */
    syncedToEbay: boolean;
    /**
     * Set when the postage was bought through here rather than typed in.
     * labelCost is a real expense, so it feeds the cost basis.
     */
    labelUrl?: string;
    labelCost?: number;
    shipmentId?: string;
  };
  /** History of auto-relist cycles on eBay */
  relistHistory?: RelistRecord[];
  /** Override relist cadence for this listing (null = use global default) */
  relistCadenceDays?: number;
  /** When this listing was last relisted */
  lastRelistedAt?: string;
  /** Scheduled publish time — listing goes live at this ISO timestamp */
  scheduledPublishAt?: string;
  /**
   * What the item sold for new and why buyers want it. Stored because the
   * analysis pipeline is split across requests (serverless functions time
   * out well before comps + retail + a refine pass can run together), so
   * each stage has to persist its result for the next one to build on.
   */
  retail?: {
    productName: string;
    retailPrice: number;
    retailPriceNote: string;
    releaseEra: string;
    desirability: string;
    sellingPoints: string[];
    at: string;
  };
  createdAt: string;
}

export interface Experiment {
  id: string;
  hypothesis: string;
  instruction: string;
}

/**
 * One playbook insight turned into something clickable: a concrete pattern
 * tied to the specific listings it applies to, rather than prose the seller
 * reads once and forgets.
 */
export interface ActionCard {
  insight: string;
  action: ProposalKind;
  matchListingIds: string[];
}

export interface Playbook {
  updatedAt: string;
  summary: string;
  /** Titles, keywords, descriptions, photos */
  listingGuidelines: string;
  /** Pricing patterns that sold */
  pricingGuidelines: string;
  avoid: string;
  experiments?: Experiment[];
  experimentResults?: string;
  actionCards?: ActionCard[];
}

/** A reference listing (someone else's sale) fed to the Brain */
export interface SeedListing {
  id: string;
  description: string;
  source?: string;
  stats?: string;
  addedAt: string;
}

/** Rules for which proposals the Brain can auto-apply without seller approval. */
export interface AutoApplyRules {
  /** Auto-apply reprices up to this dollar amount */
  maxPriceDrop: number;
  /** Auto-apply reprices up to this percentage drop */
  maxPriceDropPct: number;
  /** Auto-apply retitle proposals */
  autoRetitle: boolean;
  /** Auto-apply relist proposals */
  autoRelist: boolean;
  /** Always hold full rewrites for manual review */
  requireReviewForRewrite: boolean;
  /** Only auto-apply proposals above this confidence (0-100) */
  minConfidence: number;
}

export interface SellerSettings {
  /** What you sell */
  niche: string;
  /** Platforms you list on */
  platforms: string;
  /** Shipping approach (affects listings) */
  shipping: string;
  /** Shop voice/style */
  style: string;
  /** How much autonomy the Brain has over live listings */
  automationLevel: "manual" | "semi" | "auto";
  /** Fine-grained rules for semi-auto mode */
  autoApplyRules?: AutoApplyRules;
  /**
   * Fallback packed weight in ounces, used when a listing doesn't carry its
   * own. Most sellers ship a narrow range of similar items, so setting this
   * once beats retyping it per listing.
   */
  defaultPackageWeightOz?: number;
  /** Global default relist cadence in days (e.g. 10) */
  defaultRelistDays?: number;
  /** Whether auto-relist cycling is enabled */
  relistEnabled: boolean;
  /**
   * Brain score (0-100) a freshly-drafted listing must clear to publish
   * itself instead of waiting for manual review. 0 (the default) disables
   * auto-publish entirely — this is the one setting that skips a human
   * looking at the listing at all, so it starts off.
   */
  autoPublishThreshold: number;
  /**
   * % of asking price at or above which an incoming eBay Best Offer
   * auto-accepts (e.g. 90 = accept anything at 90%+ of ask). 0 (the
   * default) disables it — this commits to a real sale at a discount, so
   * it starts off like auto-publish does.
   */
  autoAcceptOfferPct: number;
  /**
   * Nightly email summarising changes the Brain applied by itself. On by
   * default: those edits reach the seller's live eBay listings while they are
   * not looking, so silence is the wrong default. Purely a notification —
   * turning it off changes nothing about what the automation does.
   */
  emailDigest: boolean;
}

export const DEFAULT_AUTO_RULES: AutoApplyRules = {
  maxPriceDrop: 5,
  maxPriceDropPct: 10,
  autoRetitle: true,
  autoRelist: true,
  requireReviewForRewrite: true,
  minConfidence: 60,
};

export const DEFAULT_SELLER: SellerSettings = {
  niche: "",
  platforms: "eBay, Depop",
  shipping: "",
  style: "honest, detailed, no fluff",
  automationLevel: "manual",
  relistEnabled: false,
  autoPublishThreshold: 0,
  autoAcceptOfferPct: 0,
  emailDigest: true,
};

export type ProposalKind = "reprice" | "retitle" | "rewrite" | "relist" | "hold";
export type ProposalStatus = "pending" | "approved" | "dismissed" | "applied" | "auto-applied" | "failed";

/**
 * A single suggested change to a live listing, produced by the background
 * research pass. Nothing is ever applied to eBay without the seller
 * approving it, which is why status starts at "pending".
 */
export interface Proposal {
  id: string;
  listingId: string;
  kind: ProposalKind;
  /** One line the seller reads before deciding */
  summary: string;
  /** Why, in terms of the evidence that produced it */
  rationale: string;
  currentPrice?: number;
  proposedPrice?: number;
  currentTitle?: string;
  proposedTitle?: string;
  proposedDescription?: string;
  /** 0-100 confidence from the Brain */
  confidence: number;
  status: ProposalStatus;
  error?: string;
  createdAt: string;
  resolvedAt?: string;
}

export interface EbayTokens {
  env: "sandbox" | "production";
  accessToken: string;
  refreshToken: string;
  /** ISO timestamp the access token expires at */
  accessTokenExpiresAt: string;
  connectedAt: string;
  /**
   * Scopes granted at consent. A refresh token can only request the scopes
   * it was issued with, so refreshes must replay these rather than whatever
   * the code currently wants.
   */
  grantedScopes?: string;
}

// ---------------------------------------------------------------------------
// Data access
//
// Every function here is scoped to a single seller. `userId` is required, not
// optional, and every query filters on it — so an id guessed or leaked from
// another tenant resolves to nothing rather than to someone else's row. That
// is the whole tenancy boundary; there is no second layer behind it.
// ---------------------------------------------------------------------------

/** Prisma yields null for an absent column; the app's types use undefined. */
function nn<T>(v: T | null): T | undefined {
  return v === null ? undefined : v;
}

function iso(d: Date | null): string | undefined {
  return d === null ? undefined : d.toISOString();
}

/** Read a Json column back out as its declared TypeScript shape. */
function j<T>(v: unknown): T | undefined {
  return v === null || v === undefined ? undefined : (v as T);
}

/**
 * Value for a nullable Json column. Absent becomes DbNull (SQL NULL, not the
 * JSON literal `null`). The cast is unavoidable: Prisma's InputJsonValue
 * requires an index signature, which a declared interface never has.
 */
function jsonIn(v: unknown): Prisma.InputJsonValue | typeof Prisma.DbNull {
  return v === undefined || v === null
    ? Prisma.DbNull
    : (v as unknown as Prisma.InputJsonValue);
}

function toListing(r: ListingRow): Listing {
  return {
    id: r.id,
    platform: r.platform as Platform,
    title: r.title,
    description: r.description,
    price: r.price,
    category: r.category,
    condition: r.condition,
    tags: r.tags,
    photosNote: r.photosNote,
    status: r.status as ListingStatus,
    source: r.source as Listing["source"],
    outcome: j<ListingOutcome>(r.outcome),
    depop: j<DepopState>(r.depop),
    cost: j<CostBasis>(r.cost),
    comps: j<Comps>(r.comps),
    brainScore: j<BrainScore>(r.brainScore),
    diagnosis: j<Diagnosis>(r.diagnosis),
    retail: j<Listing["retail"]>(r.retail),
    shipping: j<Listing["shipping"]>(r.shipping),
    experimentId: nn(r.experimentId),
    ebayItemId: nn(r.ebayItemId),
    ebaySku: nn(r.ebaySku),
    ebayOfferId: nn(r.ebayOfferId),
    ebayListingType: nn(r.ebayListingType),
    ebayCategoryId: nn(r.ebayCategoryId),
    ebayAspects: j<EbayAspect[]>(r.ebayAspects),
    itemSpecifics: j<ItemSpecific[]>(r.itemSpecifics),
    photos: r.photos,
    imageUrls: r.imageUrls,
    packageWeightOz: nn(r.packageWeightOz),
    packageDimensionsIn: j<Listing["packageDimensionsIn"]>(r.packageDimensionsIn),
    relistHistory: j<RelistRecord[]>(r.relistHistory),
    relistCadenceDays: nn(r.relistCadenceDays),
    lastRelistedAt: iso(r.lastRelistedAt),
    publishedAt: iso(r.publishedAt),
    scheduledPublishAt: iso(r.scheduledPublishAt),
    createdAt: r.createdAt.toISOString(),
  };
}

const LISTING_REQUIRED = [
  "platform",
  "title",
  "description",
  "price",
  "category",
  "condition",
  "photosNote",
  "status",
  "source",
] as const;

const LISTING_NULLABLE = [
  "experimentId",
  "ebayItemId",
  "ebaySku",
  "ebayOfferId",
  "ebayListingType",
  "ebayCategoryId",
  "packageWeightOz",
  "relistCadenceDays",
] as const;

const LISTING_ARRAYS = ["tags", "photos", "imageUrls"] as const;

const LISTING_JSON = [
  "outcome",
  "depop",
  "cost",
  "comps",
  "brainScore",
  "diagnosis",
  "retail",
  "shipping",
  "ebayAspects",
  "itemSpecifics",
  "packageDimensionsIn",
  "relistHistory",
] as const;

const LISTING_DATES = ["lastRelistedAt", "publishedAt", "scheduledPublishAt"] as const;

/**
 * Translate a Partial<Listing> patch into Prisma update data.
 *
 * The old JSON store used Object.assign, where a key explicitly set to
 * undefined cleared the field. Prisma reads undefined as "leave unchanged",
 * so a caller clearing a field would silently no-op — the scheduled-publish
 * cron clears `scheduledPublishAt` after publishing, and without this
 * distinction the same listing would be republished every 15 minutes. A key
 * that is *present* but undefined is therefore mapped to an explicit null.
 */
function listingUpdateData(patch: Partial<Listing>): Prisma.ListingUpdateInput {
  const has = (k: string) => Object.prototype.hasOwnProperty.call(patch, k);
  const data: Record<string, unknown> = {};
  const p = patch as Record<string, unknown>;

  // Non-nullable columns: only ever set to a real value, never cleared.
  for (const k of LISTING_REQUIRED) if (has(k) && p[k] !== undefined) data[k] = p[k];
  for (const k of LISTING_ARRAYS) if (has(k)) data[k] = p[k] ?? [];
  for (const k of LISTING_NULLABLE) if (has(k)) data[k] = p[k] ?? null;
  // Nullable Json needs Prisma's sentinel; a bare null is a type error.
  for (const k of LISTING_JSON) if (has(k)) data[k] = jsonIn(p[k]);
  for (const k of LISTING_DATES) {
    if (has(k)) data[k] = p[k] ? new Date(String(p[k])) : null;
  }

  return data as Prisma.ListingUpdateInput;
}

export async function listListings(userId: string): Promise<Listing[]> {
  const rows = await prisma.listing.findMany({
    where: { userId },
    orderBy: { createdAt: "desc" },
  });
  return rows.map(toListing);
}

export async function getListing(userId: string, id: string): Promise<Listing | undefined> {
  // userId is part of the predicate, not checked afterwards — a listing that
  // is not this seller's simply does not exist as far as this call is concerned.
  const row = await prisma.listing.findFirst({ where: { id, userId } });
  return row ? toListing(row) : undefined;
}

export async function addListing(userId: string, listing: Listing) {
  await prisma.listing.create({
    data: {
      userId,
      id: listing.id,
      platform: listing.platform,
      title: listing.title,
      description: listing.description,
      price: listing.price,
      category: listing.category,
      condition: listing.condition,
      tags: listing.tags ?? [],
      photosNote: listing.photosNote,
      status: listing.status,
      source: listing.source,
      outcome: jsonIn(listing.outcome),
      depop: jsonIn(listing.depop),
      cost: jsonIn(listing.cost),
      comps: jsonIn(listing.comps),
      brainScore: jsonIn(listing.brainScore),
      diagnosis: jsonIn(listing.diagnosis),
      retail: jsonIn(listing.retail),
      shipping: jsonIn(listing.shipping),
      ebayAspects: jsonIn(listing.ebayAspects),
      itemSpecifics: jsonIn(listing.itemSpecifics),
      packageDimensionsIn: jsonIn(listing.packageDimensionsIn),
      relistHistory: jsonIn(listing.relistHistory),
      experimentId: listing.experimentId ?? null,
      ebayItemId: listing.ebayItemId ?? null,
      ebaySku: listing.ebaySku ?? null,
      ebayOfferId: listing.ebayOfferId ?? null,
      ebayListingType: listing.ebayListingType ?? null,
      ebayCategoryId: listing.ebayCategoryId ?? null,
      photos: listing.photos ?? [],
      imageUrls: listing.imageUrls ?? [],
      packageWeightOz: listing.packageWeightOz ?? null,
      relistCadenceDays: listing.relistCadenceDays ?? null,
      lastRelistedAt: listing.lastRelistedAt ? new Date(listing.lastRelistedAt) : null,
      publishedAt: listing.publishedAt ? new Date(listing.publishedAt) : null,
      scheduledPublishAt: listing.scheduledPublishAt
        ? new Date(listing.scheduledPublishAt)
        : null,
      createdAt: new Date(listing.createdAt),
    },
  });
}

export async function updateListing(userId: string, id: string, patch: Partial<Listing>) {
  // updateMany rather than update: it scopes by userId in the same statement
  // and, like the old store, does nothing when the row is not this seller's
  // instead of throwing.
  await prisma.listing.updateMany({
    where: { id, userId },
    data: listingUpdateData(patch),
  });
}

export async function deleteListing(userId: string, id: string) {
  await prisma.listing.deleteMany({ where: { id, userId } });
}

// ---------------------------------------------------------------------------
// Seller settings
// ---------------------------------------------------------------------------

function toSettings(r: SellerSettingsRow): SellerSettings {
  return {
    niche: r.niche,
    platforms: r.platforms,
    shipping: r.shipping,
    style: r.style,
    automationLevel: r.automationLevel as SellerSettings["automationLevel"],
    autoApplyRules: j<AutoApplyRules>(r.autoApplyRules),
    relistEnabled: r.relistEnabled,
    defaultRelistDays: nn(r.defaultRelistDays),
    defaultPackageWeightOz: nn(r.defaultPackageWeightOz),
    autoPublishThreshold: r.autoPublishThreshold,
    autoAcceptOfferPct: r.autoAcceptOfferPct,
    emailDigest: r.emailDigest,
  };
}

export async function getSellerSettings(userId: string): Promise<SellerSettings> {
  const row = await prisma.sellerSettings.findUnique({ where: { userId } });
  return row ? { ...DEFAULT_SELLER, ...toSettings(row) } : { ...DEFAULT_SELLER };
}

/** True when this seller has finished the "what do you sell" step. */
export async function hasSellerSettings(userId: string): Promise<boolean> {
  return (await prisma.sellerSettings.count({ where: { userId } })) > 0;
}

export async function updateSellerSettings(
  userId: string,
  patch: Partial<SellerSettings>
): Promise<SellerSettings> {
  const current = await getSellerSettings(userId);
  // Undefined entries are dropped so a partial update can never blank a field
  // the caller did not mention — same contract as the old store.
  const defined = Object.fromEntries(
    Object.entries(patch).filter(([, v]) => v !== undefined)
  ) as Partial<SellerSettings>;
  const next: SellerSettings = { ...DEFAULT_SELLER, ...current, ...defined };

  const data = {
    niche: next.niche,
    platforms: next.platforms,
    shipping: next.shipping,
    style: next.style,
    automationLevel: next.automationLevel,
    autoApplyRules: jsonIn(next.autoApplyRules),
    relistEnabled: next.relistEnabled,
    defaultRelistDays: next.defaultRelistDays ?? null,
    defaultPackageWeightOz: next.defaultPackageWeightOz ?? null,
    autoPublishThreshold: next.autoPublishThreshold,
    autoAcceptOfferPct: next.autoAcceptOfferPct,
    emailDigest: next.emailDigest,
  };

  await prisma.sellerSettings.upsert({
    where: { userId },
    create: { userId, ...data },
    update: data,
  });
  return next;
}

// ---------------------------------------------------------------------------
// Playbook
// ---------------------------------------------------------------------------

export async function getPlaybook(userId: string): Promise<Playbook | undefined> {
  const r = await prisma.playbook.findUnique({ where: { userId } });
  if (!r) return undefined;
  return {
    updatedAt: r.updatedAt.toISOString(),
    summary: r.summary,
    listingGuidelines: r.listingGuidelines,
    pricingGuidelines: r.pricingGuidelines,
    avoid: r.avoid,
    experiments: j<Experiment[]>(r.experiments),
    experimentResults: nn(r.experimentResults),
    actionCards: j<ActionCard[]>(r.actionCards),
  };
}

export async function setPlaybook(userId: string, playbook: Playbook) {
  const data = {
    summary: playbook.summary,
    listingGuidelines: playbook.listingGuidelines,
    pricingGuidelines: playbook.pricingGuidelines,
    avoid: playbook.avoid,
    experimentResults: playbook.experimentResults ?? null,
    experiments: jsonIn(playbook.experiments),
    actionCards: jsonIn(playbook.actionCards),
    updatedAt: new Date(playbook.updatedAt),
  };
  await prisma.playbook.upsert({
    where: { userId },
    create: { userId, ...data },
    update: data,
  });
}

// ---------------------------------------------------------------------------
// Seed (reference) listings
// ---------------------------------------------------------------------------

const MAX_SEEDS = 50;

export async function listSeedListings(userId: string): Promise<SeedListing[]> {
  const rows = await prisma.seedListing.findMany({
    where: { userId },
    orderBy: { addedAt: "desc" },
    take: MAX_SEEDS,
  });
  return rows.map((r) => ({
    id: r.id,
    description: r.description,
    source: nn(r.source),
    stats: nn(r.stats),
    addedAt: r.addedAt.toISOString(),
  }));
}

export async function addSeedListing(userId: string, seed: SeedListing) {
  await prisma.seedListing.create({
    data: {
      id: seed.id,
      userId,
      description: seed.description,
      source: seed.source ?? null,
      stats: seed.stats ?? null,
      addedAt: new Date(seed.addedAt),
    },
  });
  // The old store kept only the newest 50; trim rather than grow unbounded.
  const stale = await prisma.seedListing.findMany({
    where: { userId },
    orderBy: { addedAt: "desc" },
    skip: MAX_SEEDS,
    select: { id: true },
  });
  if (stale.length) {
    await prisma.seedListing.deleteMany({
      where: { userId, id: { in: stale.map((s) => s.id) } },
    });
  }
}

export async function deleteSeedListing(userId: string, id: string) {
  await prisma.seedListing.deleteMany({ where: { id, userId } });
}

// ---------------------------------------------------------------------------
// Proposals
// ---------------------------------------------------------------------------

const MAX_PROPOSALS = 300;

function toProposal(r: ProposalRow): Proposal {
  return {
    id: r.id,
    listingId: r.listingId,
    kind: r.kind as ProposalKind,
    summary: r.summary,
    rationale: r.rationale,
    currentPrice: nn(r.currentPrice),
    proposedPrice: nn(r.proposedPrice),
    currentTitle: nn(r.currentTitle),
    proposedTitle: nn(r.proposedTitle),
    proposedDescription: nn(r.proposedDescription),
    confidence: r.confidence,
    status: r.status as ProposalStatus,
    error: nn(r.error),
    createdAt: r.createdAt.toISOString(),
    resolvedAt: iso(r.resolvedAt),
  };
}

export async function listProposals(userId: string): Promise<Proposal[]> {
  const rows = await prisma.proposal.findMany({
    where: { userId },
    orderBy: { createdAt: "desc" },
    take: MAX_PROPOSALS,
  });
  return rows.map(toProposal);
}

export async function getProposal(userId: string, id: string): Promise<Proposal | undefined> {
  const r = await prisma.proposal.findFirst({ where: { id, userId } });
  return r ? toProposal(r) : undefined;
}

/**
 * Replaces any still-pending proposal for the same listing and kind, so a
 * repeated research pass refreshes advice rather than stacking duplicates.
 * Decided proposals are kept as history.
 */
export async function upsertProposal(userId: string, proposal: Proposal) {
  await prisma.$transaction([
    prisma.proposal.deleteMany({
      where: {
        userId,
        listingId: proposal.listingId,
        kind: proposal.kind,
        status: "pending",
      },
    }),
    prisma.proposal.create({
      data: {
        id: proposal.id,
        userId,
        listingId: proposal.listingId,
        kind: proposal.kind,
        summary: proposal.summary,
        rationale: proposal.rationale,
        currentPrice: proposal.currentPrice ?? null,
        proposedPrice: proposal.proposedPrice ?? null,
        currentTitle: proposal.currentTitle ?? null,
        proposedTitle: proposal.proposedTitle ?? null,
        proposedDescription: proposal.proposedDescription ?? null,
        confidence: proposal.confidence,
        status: proposal.status,
        error: proposal.error ?? null,
        createdAt: new Date(proposal.createdAt),
        resolvedAt: proposal.resolvedAt ? new Date(proposal.resolvedAt) : null,
      },
    }),
  ]);
}

export async function updateProposal(userId: string, id: string, patch: Partial<Proposal>) {
  const has = (k: string) => Object.prototype.hasOwnProperty.call(patch, k);
  const data: Record<string, unknown> = {};
  if (patch.status !== undefined) data.status = patch.status;
  if (has("error")) data.error = patch.error ?? null;
  if (has("resolvedAt")) data.resolvedAt = patch.resolvedAt ? new Date(patch.resolvedAt) : null;
  if (patch.summary !== undefined) data.summary = patch.summary;
  if (patch.rationale !== undefined) data.rationale = patch.rationale;
  if (has("proposedPrice")) data.proposedPrice = patch.proposedPrice ?? null;
  if (has("proposedTitle")) data.proposedTitle = patch.proposedTitle ?? null;
  if (has("proposedDescription")) {
    data.proposedDescription = patch.proposedDescription ?? null;
  }
  if (Object.keys(data).length === 0) return;
  await prisma.proposal.updateMany({ where: { id, userId }, data });
}

// ---------------------------------------------------------------------------
// Research timestamp (was a single global value; now per seller)
// ---------------------------------------------------------------------------

export async function setLastResearchAt(userId: string, isoTime: string) {
  await prisma.user.update({
    where: { id: userId },
    data: { lastResearchAt: new Date(isoTime) },
  });
}

export async function getLastResearchAt(userId: string): Promise<string | undefined> {
  const u = await prisma.user.findUnique({
    where: { id: userId },
    select: { lastResearchAt: true },
  });
  return u?.lastResearchAt ? u.lastResearchAt.toISOString() : undefined;
}

// ---------------------------------------------------------------------------
// eBay tokens
//
// These are live OAuth credentials for a third-party account, one row per
// seller. Nothing outside this module should read them.
// ---------------------------------------------------------------------------

export async function getEbayTokens(userId: string): Promise<EbayTokens | undefined> {
  const r = await prisma.ebayTokens.findUnique({ where: { userId } });
  if (!r) return undefined;
  return {
    env: r.env as EbayTokens["env"],
    accessToken: r.accessToken,
    refreshToken: r.refreshToken,
    accessTokenExpiresAt: r.accessTokenExpiresAt.toISOString(),
    connectedAt: r.connectedAt.toISOString(),
    grantedScopes: nn(r.grantedScopes),
  };
}

export async function setEbayTokens(userId: string, tokens: EbayTokens) {
  const data = {
    env: tokens.env,
    accessToken: tokens.accessToken,
    refreshToken: tokens.refreshToken,
    accessTokenExpiresAt: new Date(tokens.accessTokenExpiresAt),
    connectedAt: new Date(tokens.connectedAt),
    grantedScopes: tokens.grantedScopes ?? null,
  };
  await prisma.ebayTokens.upsert({
    where: { userId },
    create: { userId, ...data },
    update: data,
  });
}

export async function clearEbayTokens(userId: string) {
  await prisma.ebayTokens.deleteMany({ where: { userId } });
}


export interface Profit {
  revenue: number;
  cost: number;
  profit: number;
  /** Profit as a % of revenue. Null when there's no revenue to divide by. */
  marginPct: number | null;
  /** True only when we know both what it sold for and what it cost */
  complete: boolean;
}

/**
 * Profit for one listing. Only meaningful once it's sold and has a cost
 * basis; `complete` says whether both halves are actually known so callers
 * can avoid quoting a margin that's really just "we don't know the cost".
 */
export function listingProfit(l: Listing): Profit | null {
  const revenue = l.outcome?.soldPrice;
  if (l.status !== "sold" || revenue === undefined) return null;

  const purchase = l.cost?.purchasePrice;
  const shipping = l.cost?.shippingCost ?? 0;
  const fees = l.cost?.fees ?? 0;
  const cost = (purchase ?? 0) + shipping + fees;
  const profit = revenue - cost;

  return {
    revenue,
    cost,
    profit,
    marginPct: revenue > 0 ? (profit / revenue) * 100 : null,
    complete: purchase !== undefined,
  };
}

/**
 * Plain-language read on where traffic is heading: rising, flat, or
 * declining, comparing the earlier half of the recorded history against the
 * later half so one noisy sync can't flip the verdict. Needs at least 3
 * points to say anything — with less, the trend is just noise.
 */
export function trafficTrend(history: TrafficPoint[] | undefined): string | null {
  if (!history || history.length < 3) return null;
  const mid = Math.floor(history.length / 2);
  const early = history.slice(0, mid);
  const late = history.slice(mid);
  const avg = (pts: TrafficPoint[], key: "views" | "watchers") =>
    pts.reduce((sum, p) => sum + p[key], 0) / pts.length;

  const viewsEarly = avg(early, "views");
  const viewsLate = avg(late, "views");
  const watchersLate = avg(late, "watchers");
  const first = history[0];
  const last = history[history.length - 1];

  const viewsDelta = viewsEarly > 0 ? (viewsLate - viewsEarly) / viewsEarly : viewsLate > 0 ? 1 : 0;
  const direction = viewsDelta > 0.15 ? "rising" : viewsDelta < -0.15 ? "declining" : "flat";

  return (
    `views ${direction} (${first.views}→${last.views} over ${history.length} syncs), ` +
    `watchers now ${watchersLate.toFixed(1)} avg`
  );
}

/** Days from listing to sale (or to now for unsold), null-safe */
export function daysListed(l: Listing): number | null {
  const start = l.outcome?.listedAt ? Date.parse(l.outcome.listedAt) : NaN;
  if (!isFinite(start)) return null;
  const end = l.outcome?.soldAt ? Date.parse(l.outcome.soldAt) : Date.now();
  if (!isFinite(end)) return null;
  return Math.max(0, Math.round((end - start) / 86400000));
}
